package Interfícies_Gràfiques;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abarthel.daw1r25
 */
public class Ex3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex3.class.getName());

    /**
     * Creates new form Ex3
     */
    public Ex3() {
        initComponents();
    }
    
    private void actualitzarText() {
  
    if (jRadioButtonVermell.isSelected()) {
        jTextArea1.setForeground(java.awt.Color.RED);
    } else if (jRadioButtonBlau.isSelected()) {
        jTextArea1.setForeground(java.awt.Color.BLUE);
    } else if (jRadioButtonVerd.isSelected()) {
        jTextArea1.setForeground(java.awt.Color.GREEN);
    }

    int estil = java.awt.Font.PLAIN;

    if (jCheckBoxNegreta.isSelected() && jCheckBoxCursiva.isSelected()) {
        estil = java.awt.Font.BOLD | java.awt.Font.ITALIC;
    } else if (jCheckBoxNegreta.isSelected()) {
        estil = java.awt.Font.BOLD;
    } else if (jCheckBoxCursiva.isSelected()) {
        estil = java.awt.Font.ITALIC;
    }

    java.awt.Font fontActual = jTextArea1.getFont();
    jTextArea1.setFont(new java.awt.Font(fontActual.getName(), estil, fontActual.getSize()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButtonVerd = new javax.swing.JRadioButton();
        jRadioButtonBlau = new javax.swing.JRadioButton();
        jRadioButtonVermell = new javax.swing.JRadioButton();
        jCheckBoxNegreta = new javax.swing.JCheckBox();
        jCheckBoxCursiva = new javax.swing.JCheckBox();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("hola hola");
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButtonVerd);
        jRadioButtonVerd.setText("Verd");
        jRadioButtonVerd.addActionListener(this::jRadioButtonVerdActionPerformed);

        buttonGroup1.add(jRadioButtonBlau);
        jRadioButtonBlau.setText("Blau");
        jRadioButtonBlau.addActionListener(this::jRadioButtonBlauActionPerformed);

        buttonGroup1.add(jRadioButtonVermell);
        jRadioButtonVermell.setText("Vermell");
        jRadioButtonVermell.addActionListener(this::jRadioButtonVermellActionPerformed);

        jCheckBoxNegreta.setText("Negreta");
        jCheckBoxNegreta.addActionListener(this::jCheckBoxNegretaActionPerformed);

        jCheckBoxCursiva.setText("Cursiva");
        jCheckBoxCursiva.addActionListener(this::jCheckBoxCursivaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonBlau)
                    .addComponent(jRadioButtonVermell)
                    .addComponent(jRadioButtonVerd))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxNegreta)
                    .addComponent(jCheckBoxCursiva))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jRadioButtonVerd)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonBlau)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonVermell))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jCheckBoxNegreta)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxCursiva)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCursivaActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxCursivaActionPerformed

    private void jRadioButtonVerdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerdActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonVerdActionPerformed

    private void jRadioButtonBlauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBlauActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonBlauActionPerformed

    private void jRadioButtonVermellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVermellActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonVermellActionPerformed

    private void jCheckBoxNegretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegretaActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxNegretaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBoxCursiva;
    private javax.swing.JCheckBox jCheckBoxNegreta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonBlau;
    private javax.swing.JRadioButton jRadioButtonVerd;
    private javax.swing.JRadioButton jRadioButtonVermell;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
