/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfícies_Gràfiques;

import java.awt.Color;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class Ex6 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex6.class.getName());

    /**
     * Creates new form Ex6
     */
    public Ex6() {
        initComponents();
    }

    private void actualitzarText() {

        jTextAreaBotons.setForeground(JColorChooser.showDialog(this, "Tria un color", Color.yellow));

        int estil = java.awt.Font.PLAIN;

        if (jCheckBoxNegreta.isSelected() && jCheckBoxCursiva.isSelected()) {
            estil = java.awt.Font.BOLD | java.awt.Font.ITALIC;
        } else if (jCheckBoxNegreta.isSelected()) {
            estil = java.awt.Font.BOLD;
        } else if (jCheckBoxCursiva.isSelected()) {
            estil = java.awt.Font.ITALIC;
        }

        java.awt.Font fontActual = jTextAreaBotons.getFont();
        jTextAreaBotons.setFont(new java.awt.Font(fontActual.getName(), estil, fontActual.getSize()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNif = new javax.swing.JTextField();
        jButtonValidar = new javax.swing.JButton();
        jPasswordFieldPwd = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFitxer = new javax.swing.JTextArea();
        jButtonGravar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBotons = new javax.swing.JTextArea();
        jCheckBoxNegreta = new javax.swing.JCheckBox();
        jCheckBoxCursiva = new javax.swing.JCheckBox();
        jButtonTriaColor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxNav = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("Tabbed Pane");

        jLabel1.setText("Nom:");

        jLabel2.setText("Contrasenya:");

        jLabel3.setText("NIF:");

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(this::jButtonValidarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNom)
                    .addComponent(jTextFieldNif)
                    .addComponent(jPasswordFieldPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jButtonValidar)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonValidar)
                    .addComponent(jPasswordFieldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entrada de Dades", jPanel2);

        jTextAreaFitxer.setColumns(20);
        jTextAreaFitxer.setRows(5);
        jScrollPane2.setViewportView(jTextAreaFitxer);

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(this::jButtonGravarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButtonGravar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGravar)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Escriure el Fitxer", jPanel3);

        jTextAreaBotons.setColumns(20);
        jTextAreaBotons.setRows(5);
        jTextAreaBotons.setText("AAAAAAAAAAA");
        jScrollPane1.setViewportView(jTextAreaBotons);

        jCheckBoxNegreta.setText("Negreta");
        jCheckBoxNegreta.addActionListener(this::jCheckBoxNegretaActionPerformed);

        jCheckBoxCursiva.setText("Cursiva");
        jCheckBoxCursiva.addActionListener(this::jCheckBoxCursivaActionPerformed);

        jButtonTriaColor.setText("Selecció Color");
        jButtonTriaColor.addActionListener(this::jButtonTriaColorActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBoxNegreta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxCursiva))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonTriaColor)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonTriaColor)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxNegreta)
                    .addComponent(jCheckBoxCursiva))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prova Botons", jPanel4);

        jComboBoxNav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pestanya 1", "Pestanya 2", "Pestanya 3" }));
        jComboBoxNav.addActionListener(this::jComboBoxNavActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jComboBoxNav, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jComboBoxNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ComboBox", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNavActionPerformed
        // TODO add your handling code here:
        int indexSeleccionat = jComboBoxNav.getSelectedIndex();

        if (indexSeleccionat >= 0 && indexSeleccionat < jTabbedPane1.getTabCount()) {
            jTabbedPane1.setSelectedIndex(indexSeleccionat);
        }
    }//GEN-LAST:event_jComboBoxNavActionPerformed

    private void jCheckBoxNegretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegretaActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxNegretaActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        boolean valid = true;

        String nom = jTextFieldNom.getText().trim();
        String pwd = new String(jPasswordFieldPwd.getPassword());
        String nif = jTextFieldNif.getText().trim();

        String missatgeError = "S'han trobat els següents errors; \n\n";

        if (nom.isEmpty()) {
            valid = false;
            missatgeError += "- El nom no pot estar buit.\n";
        }
        if (!pwd.equals("DAW")) {
            valid = false;
            missatgeError += "- Contrasenya no vàlida.\n";
        }

        if (!nif.matches("\\d{8}[A-Za-z]")) {
            valid = false;
            missatgeError += "- El NIF no té el format vàlid.\n";
        }
        if (valid) {
            JOptionPane.showMessageDialog(this, "Les dades han estat vàlidades");
            String resum = "Nom: " + nom + "\nNIF: " + nif + "\n";

            jTextAreaFitxer.setText(resum);
            jTabbedPane1.setSelectedIndex(1);

        } else {
            JOptionPane.showMessageDialog(this, missatgeError, "Error de Validació", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:

        String textAGravar = jTextAreaFitxer.getText().trim();
        JFileChooser fc = new JFileChooser();
        int seleccio = fc.showSaveDialog(this);
        File fitxer = null;

        if (seleccio == JFileChooser.APPROVE_OPTION) {
            fitxer = fc.getSelectedFile();

            if (textAGravar.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hi ha dades per gravar.", "Atenció", JOptionPane.WARNING_MESSAGE);
            } else {
                try (java.util.Formatter f = new java.util.Formatter(fitxer)) {
                    f.format("%s\n------------------\n", textAGravar);
                    JOptionPane.showMessageDialog(this, "Dades guardades correctament al fitxer 'usuaris.txt'!", "Èxit", JOptionPane.INFORMATION_MESSAGE);
                    jTextAreaFitxer.setText("");

                } catch (java.io.FileNotFoundException error) {
                    JOptionPane.showMessageDialog(this, "Error de fitxer: No s'ha pogut crear o trobar l'arxiu. Detall: " + error.getMessage(), "Error Crític", JOptionPane.ERROR_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jCheckBoxCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCursivaActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxCursivaActionPerformed

    private void jButtonTriaColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTriaColorActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jButtonTriaColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex6().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonTriaColor;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JCheckBox jCheckBoxCursiva;
    private javax.swing.JCheckBox jCheckBoxNegreta;
    private javax.swing.JComboBox<String> jComboBoxNav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordFieldPwd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaBotons;
    private javax.swing.JTextArea jTextAreaFitxer;
    private javax.swing.JTextField jTextFieldNif;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
