/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfícies_Gràfiques;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
  

    public class Ex7 extends javax.swing.JFrame {

        DefaultListModel<String> modelTasques = new DefaultListModel<>();
        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex7.class.getName());

        /**
         * Creates new form Ex7
         */
        public Ex7() {
            initComponents();

            jListTasques.setModel(modelTasques);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTasca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPrio = new javax.swing.JComboBox<>();
        jButtonAfegir = new javax.swing.JButton();
        jButtonFetes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTasques = new javax.swing.JTextArea();
        jButtonElim = new javax.swing.JButton();
        jButtonPendents = new javax.swing.JButton();
        jButtonMostrarFetes = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTasques = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tasca:");

        jLabel2.setText("Prioritat:");

        jComboBoxPrio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Mitjana", "Baixa" }));

        jButtonAfegir.setText("Afegir Tasca");
        jButtonAfegir.addActionListener(this::jButtonAfegirActionPerformed);

        jButtonFetes.setText("Marcar com a fetes");
        jButtonFetes.addActionListener(this::jButtonFetesActionPerformed);

        jTextAreaTasques.setColumns(20);
        jTextAreaTasques.setRows(5);
        jScrollPane2.setViewportView(jTextAreaTasques);

        jButtonElim.setText("Eliminar selecció");
        jButtonElim.addActionListener(this::jButtonElimActionPerformed);

        jButtonPendents.setText("Mostrar pendents");
        jButtonPendents.addActionListener(this::jButtonPendentsActionPerformed);

        jButtonMostrarFetes.setText("Mostrar fetes");
        jButtonMostrarFetes.addActionListener(this::jButtonMostrarFetesActionPerformed);

        jScrollPane3.setViewportView(jListTasques);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTasca, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButtonAfegir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFetes)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButtonElim)
                .addGap(51, 51, 51)
                .addComponent(jButtonPendents)
                .addGap(52, 52, 52)
                .addComponent(jButtonMostrarFetes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTasca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAfegir)
                    .addComponent(jButtonFetes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonElim)
                    .addComponent(jButtonPendents)
                    .addComponent(jButtonMostrarFetes))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfegirActionPerformed
        // TODO add your handling code here:
        String nomTasca = jTextFieldTasca.getText().trim();
        String prioritat = jComboBoxPrio.getSelectedItem().toString();

        if (!nomTasca.isEmpty()) {
            String tasca = "✘ " + nomTasca + " [" + prioritat + "]";
            modelTasques.addElement(tasca);

            jTextFieldTasca.setText("");
            jTextFieldTasca.requestFocus();
            jComboBoxPrio.setSelectedItem(0);
        } else {
            JOptionPane.showMessageDialog(this, "Escriu el nom de la tasca");
        }

    }//GEN-LAST:event_jButtonAfegirActionPerformed

    private void jButtonElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElimActionPerformed
        // TODO add your handling code here:
        int posicio = jListTasques.getSelectedIndex();

        if (posicio != -1) {
            modelTasques.remove(posicio);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una tasca abans d'eliminar");
        }
    }//GEN-LAST:event_jButtonElimActionPerformed

    private void jButtonFetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFetesActionPerformed
        // TODO add your handling code here:
        int posicio = jListTasques.getSelectedIndex();

        if (posicio != -1) {
            String text = modelTasques.getElementAt(posicio);
            if (text.startsWith("✘")) {
                text = "✔" + text.substring(1);
                modelTasques.setElementAt(text, posicio);
            } else {
                JOptionPane.showMessageDialog(this, "Aquesta tasca ja està completada.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una tasca primer", "Avís", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonFetesActionPerformed

    private void jButtonPendentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPendentsActionPerformed
        // TODO add your handling code here:
        jTextAreaTasques.setText(">>> Tasques Pendents <<<\n\n");
        int i = 0;
        int totalElements = modelTasques.getSize();

        while (i < totalElements) {
            String tasca = modelTasques.getElementAt(i);
            if (tasca.startsWith("✘")) {
                jTextAreaTasques.append(tasca + "\n");
            }
            i++;
        }
    }//GEN-LAST:event_jButtonPendentsActionPerformed

    private void jButtonMostrarFetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarFetesActionPerformed
        // TODO add your handling code here:
        jTextAreaTasques.setText(">>> Tasques Fetes <<<\n\n");
        int i = 0;
        int totalElements = modelTasques.getSize();

        while (i < totalElements) {
            String tasca = modelTasques.getElementAt(i);
            if (tasca.startsWith("✔")) {
                jTextAreaTasques.append(tasca + "\n");
            }
            i++;
        }
    }//GEN-LAST:event_jButtonMostrarFetesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex7().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfegir;
    private javax.swing.JButton jButtonElim;
    private javax.swing.JButton jButtonFetes;
    private javax.swing.JButton jButtonMostrarFetes;
    private javax.swing.JButton jButtonPendents;
    private javax.swing.JComboBox<String> jComboBoxPrio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListTasques;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaTasques;
    private javax.swing.JTextField jTextFieldTasca;
    // End of variables declaration//GEN-END:variables
}
