/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfícies_Gràfiques;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Ex9 extends javax.swing.JFrame {

    DefaultListModel<String> modelLlista = new DefaultListModel<>();
    DefaultTableModel modelTaula;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ex9.class.getName());

    /**
     * Creates new form Ex9
     */
    public Ex9() {
        initComponents();
        jListComandes.setModel(modelLlista);
        modelTaula = (DefaultTableModel) jTableFinal.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonEliminarLlista = new javax.swing.JButton();
        jButtonAfegirLlista1 = new javax.swing.JButton();
        jButtonPassarATaula = new javax.swing.JButton();
        jButtonEliminarFila = new javax.swing.JButton();
        jButtonResum = new javax.swing.JButton();
        jButtonNetejar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListComandes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProducte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProducte = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantitat = new javax.swing.JTextField();
        jCheckBoxUrgent = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldClient = new javax.swing.JTextField();
        jLabelEstat = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFinal = new javax.swing.JTable();
        jButtonAfegirProducte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonEliminarLlista.setText("Eliminar la llista");
        jButtonEliminarLlista.addActionListener(this::jButtonEliminarLlistaActionPerformed);

        jButtonAfegirLlista1.setText("Afegir a la llista");
        jButtonAfegirLlista1.addActionListener(this::jButtonAfegirLlista1ActionPerformed);

        jButtonPassarATaula.setText("Passar a taula");
        jButtonPassarATaula.addActionListener(this::jButtonPassarATaulaActionPerformed);

        jButtonEliminarFila.setText("Eliminar fila");
        jButtonEliminarFila.addActionListener(this::jButtonEliminarFilaActionPerformed);

        jButtonResum.setText("Resum");
        jButtonResum.addActionListener(this::jButtonResumActionPerformed);

        jButtonNetejar.setText("Netejar");
        jButtonNetejar.addActionListener(this::jButtonNetejarActionPerformed);

        jScrollPane2.setViewportView(jListComandes);

        jLabel1.setText("Nou Producte:");

        jLabel2.setText("Producte:");

        jComboBoxProducte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portàtil", "Ratolí", "Teclat", "Monitor", "Impressora" }));
        jComboBoxProducte.addActionListener(this::jComboBoxProducteActionPerformed);

        jLabel3.setText("Quantitat:");

        jCheckBoxUrgent.setText("Urgent");

        jLabel4.setText("Client:");

        jLabelEstat.setText("Estat: Cap producte a la taula - Total unitats: 0");

        jTableFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client", "Producte", "Quantitat", "Urgent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFinalMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFinal);

        jButtonAfegirProducte.setText("Afegir Producte");
        jButtonAfegirProducte.addActionListener(this::jButtonAfegirProducteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldProducte, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAfegirProducte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldClient, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBoxProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(jCheckBoxUrgent))
                                            .addComponent(jLabelEstat)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAfegirLlista1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonEliminarLlista)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPassarATaula)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonEliminarFila)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonResum, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonNetejar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxUrgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProducte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAfegirProducte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAfegirLlista1)
                    .addComponent(jButtonEliminarLlista)
                    .addComponent(jButtonPassarATaula)
                    .addComponent(jButtonEliminarFila)
                    .addComponent(jButtonResum)
                    .addComponent(jButtonNetejar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAfegirProducteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfegirProducteActionPerformed
        // TODO add your handling code here
        String nouProducte = jTextFieldProducte.getText().trim();
        
        if (!nouProducte.isEmpty()) {
            jComboBoxProducte.addItem(nouProducte);
            jComboBoxProducte.setSelectedItem(nouProducte);
            
            jTextFieldProducte.setText("");
            JOptionPane.showMessageDialog(this,"Producte afegit correctament.");
        } else {
            JOptionPane.showMessageDialog(this,"El nom del producte no pot estar buit.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAfegirProducteActionPerformed

    private void jButtonPassarATaulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassarATaulaActionPerformed
        // TODO add your handling code here:
        int posicioLlista = jListComandes.getSelectedIndex();
        
        if (posicioLlista != -1) {
            String dadesLlista = modelLlista.getElementAt(posicioLlista);
            
            String[] parts = dadesLlista.split(" \\| ");
            Object[] filaTaula = new Object[] { parts[0], parts[1], parts[2], parts[3] };
            
            modelTaula.addRow(filaTaula);
            modelLlista.remove(posicioLlista);
            
            int numElements = modelTaula.getRowCount();
            int total = 0;
            int i = 0;
            
            while (i < numElements) {
                String textQuant = modelTaula.getValueAt(i, 2).toString();
                int quantNum = Integer.parseInt(textQuant);
                total += quantNum;
                i++;
            }
            
            String estat = "Estat: " + numElements + " a la taula - Total unitats: " + total;
            jLabelEstat.setText(estat);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un element de la llista.");
        }
    }//GEN-LAST:event_jButtonPassarATaulaActionPerformed

    private void jButtonEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFilaActionPerformed
        // TODO add your handling code here:
        int filaTaula = jTableFinal.getSelectedRow();
        
        if (filaTaula != -1) {
            modelTaula.removeRow(filaTaula);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila de la taula per eliminar");
        }
    }//GEN-LAST:event_jButtonEliminarFilaActionPerformed

    private void jButtonResumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResumActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(">>> COMANDES <<<\n");
        
        int i = 0;
        int totalFiles = modelTaula.getRowCount();
        
        while (i < totalFiles) {
            String cl = modelTaula.getValueAt(i, 0).toString();
            String pr = modelTaula.getValueAt(i, 1).toString();
            String qt = modelTaula.getValueAt(i, 2).toString();
            String ur = modelTaula.getValueAt(i, 3).toString();
    
            jTextArea1.append("Client: " + cl + " | Producte: " + qt + "x " + pr + " (" + ur + ")\n");
            i++;
        }
    }//GEN-LAST:event_jButtonResumActionPerformed

    private void jTableFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFinalMouseClicked
        // TODO add your handling code here:
        int fila = jTableFinal.getSelectedRow();
        
        if (fila != -1) {
            String clientStr = modelTaula.getValueAt(fila, 0).toString();
            String producteStr = modelTaula.getValueAt(fila, 1).toString();
            String quantitatStr = modelTaula.getValueAt(fila, 2).toString();
            String urgentStr = modelTaula.getValueAt(fila, 3).toString();
            
            jTextFieldClient.setText(clientStr);
            jTextFieldQuantitat.setText(quantitatStr);
            jComboBoxProducte.setSelectedItem(producteStr);
            
            if (urgentStr.equals("Urgent")) {
                jCheckBoxUrgent.setSelected(true);
            } else {
                jCheckBoxUrgent.setSelected(false);
            }     
        }
    }//GEN-LAST:event_jTableFinalMouseClicked

    private void jComboBoxProducteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProducteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProducteActionPerformed

    private void jButtonNetejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNetejarActionPerformed
        // TODO add your handling code here:
        jTextFieldClient.setText("");
        jTextFieldQuantitat.setText("");
        jTextFieldProducte.setText(""); 
        jCheckBoxUrgent.setSelected(false);
        
        if (jComboBoxProducte.getItemCount() > 0) {
            jComboBoxProducte.setSelectedIndex(0);
        }
        jTextFieldClient.requestFocus();
    }//GEN-LAST:event_jButtonNetejarActionPerformed

    private void jButtonEliminarLlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarLlistaActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(this, 
        "Vols buidar la llista de comandes?", 
        "Confirmació", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);

        if (resposta == JOptionPane.YES_OPTION) {
            modelLlista.removeAllElements();  
        }
    }//GEN-LAST:event_jButtonEliminarLlistaActionPerformed

    private void jButtonAfegirLlista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfegirLlista1ActionPerformed
        // TODO add your handling code here:
        String client = jTextFieldClient.getText().trim();
        String producte = jComboBoxProducte.getSelectedItem().toString();
        String quantitat = jTextFieldQuantitat.getText().trim();
        boolean esUrgent = jCheckBoxUrgent.isSelected();
        
        boolean dadesValides = true;
        String errors = "";
        
        if (client.isEmpty()) { dadesValides = false; errors += "- Client buit\n"; }
        if (quantitat.isEmpty()) { dadesValides = false; errors += "- Quantitat buida\n"; }
        
        if (dadesValides) {
            String urgent = esUrgent ? "Urgent" : "Normal";
            String linia = client + " | " + producte + " | " + quantitat + " | " + urgent;
            modelLlista.addElement(linia);
            
            jTextFieldClient.setText("");
            jTextFieldQuantitat.setText("");
            jCheckBoxUrgent.setSelected(false);
        } else {
            JOptionPane.showMessageDialog(this, errors, "Error de dades", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAfegirLlista1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ex9().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfegirLlista1;
    private javax.swing.JButton jButtonAfegirProducte;
    private javax.swing.JButton jButtonEliminarFila;
    private javax.swing.JButton jButtonEliminarLlista;
    private javax.swing.JButton jButtonNetejar;
    private javax.swing.JButton jButtonPassarATaula;
    private javax.swing.JButton jButtonResum;
    private javax.swing.JCheckBox jCheckBoxUrgent;
    private javax.swing.JComboBox<String> jComboBoxProducte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEstat;
    private javax.swing.JList<String> jListComandes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFinal;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldClient;
    private javax.swing.JTextField jTextFieldProducte;
    private javax.swing.JTextField jTextFieldQuantitat;
    // End of variables declaration//GEN-END:variables
}
