/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfícies_Gràfiques;

/**
 *
 * @author abarthel.daw1r25
 */
public class ExMenú extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExMenú.class.getName());

    /**
     * Creates new form ExMenú
     */
    public ExMenú() {
        initComponents();
        actualitzarText();
    }

    private void actualitzarText() {

        if (jRadioButtonVermell.isSelected()) {
            jTextArea1.setForeground(java.awt.Color.RED);
        } else if (jRadioButtonBlau.isSelected()) {
            jTextArea1.setForeground(java.awt.Color.BLUE);
        } else if (jRadioButtonVerd.isSelected()) {
            jTextArea1.setForeground(java.awt.Color.GREEN);
        }

        int estil = java.awt.Font.PLAIN;

        if (jCheckBoxNegreta.isSelected() && jCheckBoxCursiva.isSelected()) {
            estil = java.awt.Font.BOLD | java.awt.Font.ITALIC;
        } else if (jCheckBoxNegreta.isSelected()) {
            estil = java.awt.Font.BOLD;
        } else if (jCheckBoxCursiva.isSelected()) {
            estil = java.awt.Font.ITALIC;
        }

        java.awt.Font fontActual = jTextArea1.getFont();
        jTextArea1.setFont(new java.awt.Font(fontActual.getName(), estil, fontActual.getSize()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxCursiva2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxNegreta2 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonVerd = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonVermell = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonBlau = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxCursiva = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxNegreta = new javax.swing.JCheckBoxMenuItem();

        jMenu3.setText("Colors");

        buttonGroup2.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("Verd");
        jRadioButtonMenuItem4.addActionListener(this::jRadioButtonMenuItem4ActionPerformed);
        jMenu3.add(jRadioButtonMenuItem4);

        buttonGroup2.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Vermell");
        jRadioButtonMenuItem5.addActionListener(this::jRadioButtonMenuItem5ActionPerformed);
        jMenu3.add(jRadioButtonMenuItem5);

        buttonGroup2.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("Blau");
        jRadioButtonMenuItem6.addActionListener(this::jRadioButtonMenuItem6ActionPerformed);
        jMenu3.add(jRadioButtonMenuItem6);

        jPopupMenu1.add(jMenu3);

        jMenu4.setText("Text");

        jCheckBoxCursiva2.setSelected(true);
        jCheckBoxCursiva2.setText("Cursiva");
        jCheckBoxCursiva2.addActionListener(this::jCheckBoxCursiva2ActionPerformed);
        jMenu4.add(jCheckBoxCursiva2);

        jCheckBoxNegreta2.setSelected(true);
        jCheckBoxNegreta2.setText("Negreta");
        jCheckBoxNegreta2.addActionListener(this::jCheckBoxNegreta2ActionPerformed);
        jMenu4.add(jCheckBoxNegreta2);

        jPopupMenu1.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("                         HOLA");
        jTextArea1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jMenu1.setMnemonic('c');
        jMenu1.setText("Colors");

        jRadioButtonVerd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonGroup1.add(jRadioButtonVerd);
        jRadioButtonVerd.setMnemonic('e');
        jRadioButtonVerd.setSelected(true);
        jRadioButtonVerd.setText("Verd");
        jRadioButtonVerd.addActionListener(this::jRadioButtonVerdActionPerformed);
        jMenu1.add(jRadioButtonVerd);

        jRadioButtonVermell.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonGroup1.add(jRadioButtonVermell);
        jRadioButtonVermell.setMnemonic('v');
        jRadioButtonVermell.setText("Vermell");
        jRadioButtonVermell.addActionListener(this::jRadioButtonVermellActionPerformed);
        jMenu1.add(jRadioButtonVermell);

        jRadioButtonBlau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        buttonGroup1.add(jRadioButtonBlau);
        jRadioButtonBlau.setMnemonic('b');
        jRadioButtonBlau.setText("Blau");
        jRadioButtonBlau.addActionListener(this::jRadioButtonBlauActionPerformed);
        jMenu1.add(jRadioButtonBlau);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('t');
        jMenu2.setText("Text");

        jCheckBoxCursiva.setSelected(true);
        jCheckBoxCursiva.setText("Cursiva");
        jCheckBoxCursiva.addActionListener(this::jCheckBoxCursivaActionPerformed);
        jMenu2.add(jCheckBoxCursiva);

        jCheckBoxNegreta.setSelected(true);
        jCheckBoxNegreta.setText("Negreta");
        jCheckBoxNegreta.addActionListener(this::jCheckBoxNegretaActionPerformed);
        jMenu2.add(jCheckBoxNegreta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonVermellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVermellActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonVermellActionPerformed

    private void jRadioButtonVerdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerdActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonVerdActionPerformed

    private void jRadioButtonBlauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBlauActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonBlauActionPerformed

    private void jCheckBoxCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCursivaActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxCursivaActionPerformed

    private void jCheckBoxNegretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegretaActionPerformed
        // TODO add your handling code here:
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxNegretaActionPerformed

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        // TODO add your handling code here:
        jRadioButtonVerd.setSelected(true);
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jRadioButtonMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem5ActionPerformed
        // TODO add your handling code here:
        jRadioButtonVermell.setSelected(true);
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonMenuItem5ActionPerformed

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6ActionPerformed
        // TODO add your handling code here:
        jRadioButtonBlau.setSelected(true);
        actualitzarText();
    }//GEN-LAST:event_jRadioButtonMenuItem6ActionPerformed

    private void jCheckBoxCursiva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCursiva2ActionPerformed
        // TODO add your handling code here:
        // Fem que la Negreta de dalt copiï si la Negreta del Popup està marcada o no
        jCheckBoxCursiva.setSelected(jCheckBoxCursiva2.isSelected());
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxCursiva2ActionPerformed

    private void jCheckBoxNegreta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNegreta2ActionPerformed
        // TODO add your handling code here:
        jCheckBoxNegreta.setSelected(jCheckBoxNegreta2.isSelected());
        actualitzarText();
    }//GEN-LAST:event_jCheckBoxNegreta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExMenú().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxCursiva;
    private javax.swing.JCheckBoxMenuItem jCheckBoxCursiva2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxNegreta;
    private javax.swing.JCheckBoxMenuItem jCheckBoxNegreta2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonBlau;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonVerd;
    private javax.swing.JRadioButtonMenuItem jRadioButtonVermell;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
