/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfícies_Gràfiques.TEST;

import java.awt.Color;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class ExTech extends javax.swing.JFrame {

    DefaultListModel<String> modelLlista = new DefaultListModel<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExTech.class.getName());

    /**
     * Creates new form ExTech
     */
    public ExTech() {
        initComponents();
        lstAssignats.setModel(modelLlista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabMenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        btnFoto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnColor = new javax.swing.JButton();
        lblRuta = new javax.swing.JLabel();
        btnSeguent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtProjecte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbDepartament = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rdbCompleta = new javax.swing.JRadioButton();
        rdbMitja = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        chkPerill = new javax.swing.JCheckBox();
        chkNocturn = new javax.swing.JCheckBox();
        chkIdiomes = new javax.swing.JCheckBox();
        btnAssignar = new javax.swing.JButton();
        btnAfegir = new javax.swing.JButton();
        txtDepartament = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAssignats = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuitemTancar = new javax.swing.JMenuItem();
        mnuItemSortir = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabMenu.setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("DNI: ");

        jLabel2.setText("Contrassenya:");

        btnFoto.setText("Carregar Foto");
        btnFoto.addActionListener(this::btnFotoActionPerformed);

        jLabel3.setText("Foto de Perfil:");

        jPanelColor.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        btnColor.setText("Canviar de Color");
        btnColor.addActionListener(this::btnColorActionPerformed);

        btnSeguent.setText("Següent");
        btnSeguent.addActionListener(this::btnSeguentActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColor))
                            .addComponent(btnSeguent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pwdPass))))
                        .addGap(18, 18, 18)
                        .addComponent(lblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFoto)
                    .addComponent(jLabel3)
                    .addComponent(lblRuta))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnColor)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeguent)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabMenu.addTab("Perfil", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Nom del Projecte:");

        jLabel6.setText("Departament:");

        cmbDepartament.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recursos Humans", "Tecnologia", "Programació", "Informàtica" }));

        jLabel7.setText("Dedicació:");

        buttonGroup1.add(rdbCompleta);
        rdbCompleta.setText("Jornada Completa");

        buttonGroup1.add(rdbMitja);
        rdbMitja.setText("Mitja Jornada");

        jLabel8.setText("Extres:");

        chkPerill.setText("Perillositat");

        chkNocturn.setText("Nocturnitat");

        chkIdiomes.setText("Idiomes");

        btnAssignar.setText("Assignar");
        btnAssignar.addActionListener(this::btnAssignarActionPerformed);

        btnAfegir.setText("Afegir Departament");
        btnAfegir.addActionListener(this::btnAfegirActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(chkPerill)
                        .addGap(18, 18, 18)
                        .addComponent(chkNocturn)
                        .addGap(18, 18, 18)
                        .addComponent(chkIdiomes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssignar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(rdbCompleta)
                                .addGap(18, 18, 18)
                                .addComponent(rdbMitja)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProjecte)
                                    .addComponent(cmbDepartament, 0, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(txtDepartament)
                                .addGap(18, 18, 18)))
                        .addComponent(btnAfegir)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProjecte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegir)
                    .addComponent(txtDepartament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdbCompleta)
                    .addComponent(rdbMitja))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkPerill)
                        .addComponent(chkNocturn)
                        .addComponent(chkIdiomes)
                        .addComponent(btnAssignar)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        tabMenu.addTab("Projecte", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jScrollPane1.setViewportView(lstAssignats);

        jLabel9.setText("Projectes Assignats:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        tabMenu.addTab("Menú", jPanel3);

        mnuSistema.setText("Sistema");

        mnuitemTancar.setText("Tancar Sessió");
        mnuitemTancar.addActionListener(this::mnuitemTancarActionPerformed);
        mnuSistema.add(mnuitemTancar);

        mnuItemSortir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemSortir.setText("Sortir");
        mnuItemSortir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuItemSortirMouseClicked(evt);
            }
        });
        mnuItemSortir.addActionListener(this::mnuItemSortirActionPerformed);
        mnuSistema.add(mnuItemSortir);

        jMenuBar1.add(mnuSistema);

        mnuAjuda.setText("Ajuda");
        mnuAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguentActionPerformed
        String dni = txtDni.getText().trim();
        String pwd = new String(pwdPass.getPassword());

        if (dni.isEmpty() || pwd.length() < 4) {
            JOptionPane.showMessageDialog(this, "Error al introduïr les dades");
        } else {
            tabMenu.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btnSeguentActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        JFileChooser fc = new JFileChooser();
        File f = null;
        int seleccio = fc.showDialog(this, "Tria una imatge");

        if (seleccio == JFileChooser.APPROVE_OPTION) {
            f = fc.getSelectedFile();
            lblRuta.setText(f.getAbsolutePath());
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        // TODO add your handling code here:
        jPanelColor.setBackground(JColorChooser.showDialog(this, "Tria un color", Color.yellow));
    }//GEN-LAST:event_btnColorActionPerformed

    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        // TODO add your handling code here:
        String dept = txtDepartament.getText().trim();

        if (!dept.isEmpty()) {
            cmbDepartament.addItem(dept);
            cmbDepartament.setSelectedItem(dept);
        } else {
            JOptionPane.showConfirmDialog(this, "Introdueix un departament.");
        }

    }//GEN-LAST:event_btnAfegirActionPerformed

    private void btnAssignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignarActionPerformed
        // TODO add your handling code here:
        String nom = txtProjecte.getText().trim();
        String dept = cmbDepartament.getSelectedItem().toString();
        boolean dedicacio = rdbCompleta.isSelected();
        String ded = dedicacio ? "Jornada Completa" : "Mitja jornada";
        String extra = "";

        if (chkIdiomes.isSelected()) {
            extra += "Idiomes ";
        }
        if (chkNocturn.isSelected()) {
            extra += "Nocturnitat ";
        }
        if (chkPerill.isSelected()) {
            extra += "Perillositat ";
        }

        if (nom.isEmpty() || dept.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dades buides.");
        } else {
            String linia = "PROJECTE: " + nom + " - " + dept + " - " + ded + " - " + extra;
            modelLlista.addElement(linia);
            tabMenu.setSelectedIndex(2);
        }
    }//GEN-LAST:event_btnAssignarActionPerformed

    private void mnuAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAjudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "App creada per Àlex");
    }//GEN-LAST:event_mnuAjudaMouseClicked

    private void mnuItemSortirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemSortirMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuItemSortirMouseClicked

    private void mnuItemSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSortirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuItemSortirActionPerformed

    private void mnuitemTancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemTancarActionPerformed
        // TODO add your handling code here:
        modelLlista.clear();
        txtDepartament.setText("");
        txtDni.setText("");
        txtProjecte.setText("");
        rdbMitja.setSelected(false);
        chkIdiomes.setSelected(false);
        chkPerill.setSelected(false);
        chkNocturn.setSelected(false);
        pwdPass.setText("");
        tabMenu.setSelectedIndex(0);
    }//GEN-LAST:event_mnuitemTancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExTech().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnAssignar;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnSeguent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkIdiomes;
    private javax.swing.JCheckBox chkNocturn;
    private javax.swing.JCheckBox chkPerill;
    private javax.swing.JComboBox<String> cmbDepartament;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JList<String> lstAssignats;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuItemSortir;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuitemTancar;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JRadioButton rdbCompleta;
    private javax.swing.JRadioButton rdbMitja;
    private javax.swing.JTabbedPane tabMenu;
    private javax.swing.JTextField txtDepartament;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtProjecte;
    // End of variables declaration//GEN-END:variables
}
